export interface LandingPage {
  slug: string;
  title: string;
  tagline: string;
  metaTitle: string;
  metaDescription: string;
  primaryKeyword: string;
  startingPrice: string;
  turnaround: string;
  heroDescription: string;
  whatIs: { question: string; answer: string };
  included: string[];
  process: { step: string; title: string; description: string }[];
  whoFor: string[];
  faqs: { q: string; a: string }[];
  relatedServices: { title: string; href: string }[];
  internalLinks: { title: string; href: string }[];
  stats: { value: string; label: string }[];
}

export const landingPages: LandingPage[] = [
  {
    slug: "logo-design-service",
    title: "Logo Design Service",
    tagline: "Custom logos designed from scratch — no templates, no AI generation, no compromise.",
    metaTitle: "Logo Design Service — From $150 | Evoke Studio",
    metaDescription: "Logo design service starting from $150. Custom marks, wordmarks, and brand symbols designed from scratch. SVG, AI, EPS, PDF delivered in 5–7 days. Free quote in 24hrs.",
    primaryKeyword: "logo design service",
    startingPrice: "$150",
    turnaround: "5–7 business days",
    heroDescription: "Our logo design service delivers custom, hand-crafted marks built around your brand strategy — not a template library. Every logo is designed from a blank canvas, tested across contexts, and delivered as print-ready vector files.",
    whatIs: {
      question: "What is a logo design service?",
      answer: "A logo design service is a professional process where a designer creates a unique visual mark for your business — from initial concept through to final production-ready files. Unlike DIY tools or template marketplaces, a professional logo design service starts with your brand strategy: who you serve, what you stand for, and how you need to be perceived. The result is a custom mark that works at every size, in every context, and across every medium from business cards to billboard.",
    },
    included: [
      "Brand discovery questionnaire and strategy brief",
      "3 initial logo concepts (mark, wordmark, or combination)",
      "2 rounds of revisions on chosen concept",
      "Final logo in primary, reversed, and monochrome versions",
      "SVG, AI, EPS, PDF, PNG (transparent), JPEG deliverables",
      "Brand color palette (Pantone, CMYK, RGB, HEX)",
      "Typography pairing recommendation",
      "Basic usage guidelines (1-page brand reference)",
    ],
    process: [
      { step: "01", title: "Discovery", description: "You complete a brand brief — your industry, competitors, target audience, and visual preferences. We review and ask follow-up questions." },
      { step: "02", title: "Concepts", description: "We design 3 distinct logo directions within 5 business days. Each concept comes with a rationale explaining the strategic thinking behind it." },
      { step: "03", title: "Refinement", description: "You choose one direction. We refine it through 2 rounds of revisions until it's exactly right — every detail, proportion, and spacing." },
      { step: "04", title: "Delivery", description: "You receive a complete file package: every format, every colour variant, every size — ready for print, web, embroidery, and signage." },
    ],
    whoFor: [
      "Founders launching a new business",
      "Startups preparing for their first funding round",
      "Small businesses that outgrew a DIY logo",
      "Established brands undertaking a rebrand",
      "Agencies needing white-label logo design",
      "E-commerce brands building visual identity",
    ],
    faqs: [
      { q: "How much does a logo design service cost?", a: "Our logo design service starts at $150 for a standalone wordmark or simple icon mark. Full brand identity packages — including logo, colour palette, typography, and a brand guidelines document — start at $500. Complex custom marks or multi-variant systems are quoted individually after a brief review. You'll receive a fixed quote before any work begins." },
      { q: "How long does logo design take?", a: "Initial concepts are delivered within 5 business days of receiving a completed brief. Total project time — from brief to final files — is typically 10–14 business days, depending on the number of revision rounds required." },
      { q: "What file formats will I receive?", a: "You receive SVG, AI (Adobe Illustrator), EPS, PDF, PNG (transparent background), and JPEG. These cover every use case: web, print, embroidery, large-format signage, and digital advertising. All files are professionally organised and labelled." },
      { q: "Do you design logos for any industry?", a: "Yes. We have experience designing logos across technology, financial services, professional services, health and wellness, hospitality, e-commerce, real estate, and consumer brands. Our approach is strategy-first — we learn your category and competitive landscape before designing." },
      { q: "Can I see logo examples before hiring you?", a: "Yes — our portfolio at madebyevoke.com/portfolio shows real client work across multiple industries. You can also view our Behance profile for additional case studies and process breakdowns." },
      { q: "What if I don't like the initial concepts?", a: "We include 2 full revision rounds in every project. If the initial concepts miss the mark significantly, we'll discuss your feedback and redesign at no additional charge — it rarely happens because our brief process is thorough, but we stand behind our work." },
      { q: "Do you offer logo design for small businesses?", a: "Yes — in fact, most of our clients are small businesses and early-stage startups. We offer a range of price points and scope levels to match different budgets, from a standalone logo mark to a full brand identity system." },
      { q: "Is the logo 100% custom or template-based?", a: "Every logo we design is 100% custom — created from scratch for your brand. We don't use template libraries, stock mark repositories, or AI generation tools in our design process. You own the final mark outright and it is unique to your business." },
    ],
    relatedServices: [
      { title: "Brand Identity Design", href: "/lp/brand-identity-design" },
      { title: "Logo Redesign Service", href: "/lp/logo-redesign-service" },
      { title: "Brand Guidelines Design", href: "/lp/brand-guidelines-design" },
      { title: "AI Logo Vectorization", href: "/lp/ai-logo-vectorization" },
    ],
    internalLinks: [
      { title: "View all services", href: "/services" },
      { title: "See our portfolio", href: "/portfolio" },
      { title: "Get a free quote", href: "/contact" },
      { title: "How to build a brand identity", href: "/blog/how-to-build-brand-identity" },
      { title: "Brand naming guide", href: "/blog/brand-naming-guide" },
    ],
    stats: [
      { value: "500+", label: "Logos designed" },
      { value: "5–7 days", label: "Avg. turnaround" },
      { value: "$150", label: "Starting price" },
      { value: "5.0/5", label: "Clutch rating" },
    ],
  },

  {
    slug: "brand-identity-design",
    title: "Brand Identity Design",
    tagline: "Complete visual identity systems built to position your brand, not just make it look good.",
    metaTitle: "Brand Identity Design Service — From $500 | Evoke Studio",
    metaDescription: "Brand identity design from $500. Logo, colour palette, typography, and brand guidelines — everything your business needs to look consistent across every touchpoint. Free quote in 24hrs.",
    primaryKeyword: "brand identity design",
    startingPrice: "$500",
    turnaround: "10–14 business days",
    heroDescription: "Brand identity design is more than a logo. It's the complete visual language your business uses to communicate — every colour, typeface, layout principle, and graphic element working together. Our brand identity design service builds that system from scratch, grounded in strategy.",
    whatIs: {
      question: "What is brand identity design?",
      answer: "Brand identity design is the process of creating the visual system that represents your business — comprising your logo, colour palette, typography, imagery style, and graphic language. These elements are designed to work together and be applied consistently across every touchpoint: your website, business cards, social media, proposals, signage, and packaging. A strong brand identity makes your business instantly recognisable, communicates your positioning at a glance, and builds the kind of trust that converts prospects into clients. It is distinct from 'branding' broadly — brand identity is specifically the visual expression of your brand strategy.",
    },
    included: [
      "Brand strategy workshop (discovery session + positioning brief)",
      "Custom logo design (primary mark + alternate versions)",
      "Comprehensive colour palette (Pantone, CMYK, RGB, HEX)",
      "Typography system (primary and secondary typefaces)",
      "Iconography and graphic element library",
      "Brand pattern or texture (where applicable)",
      "Business card and letterhead design",
      "Social media profile and cover templates",
      "Brand guidelines document (20–30 pages PDF)",
      "Complete file package (SVG, AI, EPS, PDF, PNG, JPEG)",
    ],
    process: [
      { step: "01", title: "Strategy", description: "We begin with a brand strategy session — defining your positioning, target audience, competitive context, and visual direction. This informs every design decision." },
      { step: "02", title: "Identity Design", description: "We design your visual identity system: logo, colours, typography, and supporting graphic elements — all in one cohesive direction presented for your review." },
      { step: "03", title: "Application", description: "The identity is applied to real-world touchpoints — business card, letterhead, social templates — to show how the system performs in context." },
      { step: "04", title: "Guidelines + Delivery", description: "We compile a brand guidelines document covering usage rules, do's and don'ts, and application examples. You receive every asset, every format, fully organised." },
    ],
    whoFor: [
      "Startups launching their first brand",
      "Founders preparing for investment",
      "Businesses rebranding after growth",
      "Professional services firms building credibility",
      "E-commerce brands entering competitive categories",
      "Agencies needing white-label identity work",
    ],
    faqs: [
      { q: "How much does brand identity design cost?", a: "Our brand identity design service starts at $500 for a core identity package — logo, colour palette, typography, and a one-page brand reference. A full identity system with brand guidelines, stationery templates, and social templates starts at $1,200. Enterprise-scale identity projects or full rebrands are quoted individually. All prices are fixed — no hourly billing." },
      { q: "What is the difference between a logo and a brand identity?", a: "A logo is a single mark. A brand identity is the complete visual system — the logo, colour palette, typography, imagery style, graphic elements, and the rules for how they work together. A logo without a brand identity system often results in inconsistent execution: different fonts on your website vs. your proposals vs. your social media. Brand identity design solves that by giving you a unified visual language." },
      { q: "How long does brand identity design take?", a: "A core identity project (logo + colour + typography) takes 10–14 business days. A full system including brand guidelines and stationery takes 3–4 weeks. Complex projects or larger organisations may take longer — timeline is confirmed in your brief before work begins." },
      { q: "Do I need brand guidelines?", a: "Yes — if you work with other designers, developers, social media managers, or marketing agencies, brand guidelines are essential. Without them, your brand is applied inconsistently and degrades over time. Our guidelines document covers colour codes, font usage, logo spacing rules, photography style, and common misuse examples." },
      { q: "What industries do you work with?", a: "We have worked with technology companies, management consultants, wealth managers, real estate agencies, healthcare providers, recruitment firms, e-commerce brands, and creative agencies. Our approach is strategy-first — we learn your category before designing." },
      { q: "Can you redesign an existing brand identity?", a: "Yes — we offer full rebrand services. The process is the same as a new identity, but we begin by auditing your existing brand equity: what's working, what should be retained, and what needs to change. See our brand identity redesign landing page for details." },
      { q: "Will I own the final brand identity files?", a: "Yes. Full intellectual property ownership transfers to you upon final payment. You receive all source files (AI, EPS, PDF) so you can hand them to any future designer or agency without restriction." },
    ],
    relatedServices: [
      { title: "Logo Design Service", href: "/lp/logo-design-service" },
      { title: "Brand Guidelines Design", href: "/lp/brand-guidelines-design" },
      { title: "Logo Redesign Service", href: "/lp/logo-redesign-service" },
      { title: "Startup Branding", href: "/lp/startup-branding" },
    ],
    internalLinks: [
      { title: "Brand identity vs brand image explained", href: "/blog/brand-identity-vs-brand-image" },
      { title: "Brand brief guide", href: "/blog/brand-brief-guide" },
      { title: "Visual identity guide", href: "/blog/visual-identity-guide" },
      { title: "See our portfolio", href: "/portfolio" },
      { title: "Get a free quote", href: "/contact" },
    ],
    stats: [
      { value: "500+", label: "Identities built" },
      { value: "10–14 days", label: "Avg. turnaround" },
      { value: "$500", label: "Starting price" },
      { value: "5.0/5", label: "Clutch rating" },
    ],
  },

  {
    slug: "ai-logo-vectorization",
    title: "AI Logo Vectorization Service",
    tagline: "Turn your Midjourney, DALL·E, or Ideogram logo into a production-ready vector file — manually, not with auto-trace.",
    metaTitle: "AI Logo Vectorization Service — From $50 | Evoke Studio",
    metaDescription: "AI logo vectorization from $50. Manual reconstruction of Midjourney, DALL·E, Firefly, and Ideogram logos into SVG, AI, EPS, PDF. No auto-trace. 24–48hr delivery. Free quote.",
    primaryKeyword: "AI logo vectorization",
    startingPrice: "$50",
    turnaround: "24–48 hours",
    heroDescription: "AI logo vectorization is the process of manually rebuilding an AI-generated logo — pixel by pixel — into a clean, scalable vector file. Every shape, curve, and colour is reconstructed by hand. The result is a production-ready asset that prints sharp at any size, from a business card to a building fascia.",
    whatIs: {
      question: "What is AI logo vectorization?",
      answer: "AI logo vectorization is the process of converting an AI-generated logo image (from tools like Midjourney, DALL·E, Adobe Firefly, or Ideogram) into a professional vector file (SVG, EPS, or AI). AI-generated logos are raster images — they are made of pixels and cannot scale without quality loss. Vectorization rebuilds the logo as mathematical curves (vector paths) that scale infinitely without any degradation. At Evoke Studio, we do this manually — every path traced by hand — rather than using automated auto-trace tools that produce messy, unusable anchor points.",
    },
    included: [
      "Manual path-by-path vector reconstruction (no auto-trace)",
      "All shapes, letterforms, and icons rebuilt from scratch",
      "Colour extraction with exact HEX, RGB, CMYK, and Pantone matches",
      "Primary logo + reversed (white) version",
      "SVG (web-ready), AI (editable), EPS (print), PDF (proofing), PNG (transparent), JPEG",
      "File naming and organisation by format and variant",
      "Free revision if any element is missed or incorrect",
    ],
    process: [
      { step: "01", title: "Upload", description: "Send us your AI-generated logo image — PNG, JPEG, or PDF. Higher resolution is better, but we work with what you have." },
      { step: "02", title: "Quote", description: "We assess the complexity and send a fixed quote within 2 hours. Simple wordmarks start at $50. Complex multi-element marks are priced accordingly." },
      { step: "03", title: "Reconstruction", description: "Our designer manually traces every path, rebuilding your logo as clean vector artwork. No auto-trace shortcuts." },
      { step: "04", title: "Delivery", description: "You receive every file format — SVG, AI, EPS, PDF, PNG, JPEG — within 24–48 hours of approving the quote." },
    ],
    whoFor: [
      "Founders who generated a logo with Midjourney or DALL·E",
      "Designers who received an AI logo from a client",
      "Brands preparing files for a print vendor",
      "Studios offering white-label vectorization",
      "Developers needing production-ready SVGs",
      "Apparel and merchandise brands needing embroidery-ready files",
    ],
    faqs: [
      { q: "How much does AI logo vectorization cost?", a: "AI logo vectorization starts at $50 for a simple wordmark or icon. Most logos fall in the $50–$150 range. Complex multi-element marks with detailed illustrations cost more — we provide a fixed quote within 2 hours of receiving your file. There are no hourly rates or hidden charges." },
      { q: "How long does AI logo vectorization take?", a: "Standard delivery is 24–48 hours from quote approval. Rush delivery (same business day) is available at an additional fee. Most projects are completed faster than quoted — we'll always let you know if it'll take longer." },
      { q: "Why can't I just use an auto-trace tool?", a: "Auto-trace tools (like Adobe Illustrator's Image Trace) produce messy vector files — hundreds of unnecessary anchor points, jagged curves, and broken shapes. The result may look acceptable on screen but falls apart in print, at large scale, or when handed to another designer. Manual vectorization produces clean, professional paths that work everywhere." },
      { q: "What AI logo tools do you work with?", a: "We vectorize logos from Midjourney, DALL·E 3, Adobe Firefly, Ideogram, Stable Diffusion, Leonardo AI, and any other AI image generator. The source doesn't matter — we work from the output image." },
      { q: "Will the vectorized logo look exactly like the original?", a: "Yes — within the limits of what's possible with vector paths. For photorealistic or gradient-heavy AI logos, some elements may need to be simplified for print viability. We flag these in advance and discuss options before proceeding." },
      { q: "Can you fix problems with an AI logo during vectorization?", a: "Yes. Many clients ask us to clean up issues in their AI logo during the vectorization process — fixing letter spacing, correcting proportions, simplifying overcomplex elements, or adjusting colours. This is treated as a light revision rather than a full redesign and is usually included or minimally priced." },
      { q: "What file formats will I receive?", a: "You receive SVG (web and development), AI (Adobe Illustrator editable source), EPS (industry-standard print), PDF (proofing and sharing), PNG with transparent background (digital use), and JPEG (general use). All files are labelled and organised." },
    ],
    relatedServices: [
      { title: "AI Logo Cleanup Service", href: "/lp/ai-logo-cleanup" },
      { title: "Logo Design Service", href: "/lp/logo-design-service" },
      { title: "Brand Identity Design", href: "/lp/brand-identity-design" },
    ],
    internalLinks: [
      { title: "AI logo vectorization service page", href: "/services/ai-logo-vectorization" },
      { title: "AI logo cleanup service", href: "/services/ai-logo-cleanup" },
      { title: "Typography reconstruction", href: "/services/typography-reconstruction" },
      { title: "See vectorization examples", href: "/portfolio" },
      { title: "Get a free quote", href: "/contact" },
    ],
    stats: [
      { value: "500+", label: "Logos vectorized" },
      { value: "24–48hrs", label: "Turnaround" },
      { value: "$50", label: "Starting price" },
      { value: "100%", label: "Manual precision" },
    ],
  },

  {
    slug: "startup-branding",
    title: "Startup Branding Agency",
    tagline: "Branding for startups that need to look credible on day one — not just funded.",
    metaTitle: "Startup Branding Agency — Logo & Identity Design | Evoke Studio",
    metaDescription: "Startup branding from $500. Logo design, brand identity, and brand guidelines built for founders who need to look investor-ready and customer-ready from launch. Free quote in 24hrs.",
    primaryKeyword: "startup branding",
    startingPrice: "$500",
    turnaround: "10–14 business days",
    heroDescription: "Startup branding is about one thing: trust. Before your first customer, before your first investor meeting, before your product ships — your brand is the only thing between you and a 'no'. Our startup branding service builds the visual foundation that makes every pitch, every email, and every touchpoint land with the right authority.",
    whatIs: {
      question: "What is startup branding?",
      answer: "Startup branding is the process of creating a visual identity and brand strategy for a new business — covering logo design, colour palette, typography, and the core positioning that shapes how your company is perceived. For startups, branding serves two audiences simultaneously: potential customers who need to trust you enough to buy, and potential investors who need to believe you're building something serious. Effective startup branding signals credibility, category clarity, and ambition — all before a single word is read.",
    },
    included: [
      "Brand positioning brief and competitive audit",
      "Custom logo design (mark + wordmark + combination variants)",
      "Startup colour palette — primary and secondary (Pantone, CMYK, RGB, HEX)",
      "Typography system (headline and body typefaces)",
      "Brand guidelines document (usage rules, do's and don'ts)",
      "Pitch deck cover and title slide template",
      "LinkedIn company profile and banner template",
      "Business card design",
      "Email signature template",
      "Complete file package (SVG, AI, EPS, PDF, PNG, JPEG)",
    ],
    process: [
      { step: "01", title: "Positioning", description: "We define your brand positioning — the specific market you own, the audience you serve, and how you're different from every other option they could choose." },
      { step: "02", title: "Identity Design", description: "We design your complete visual identity: logo, colours, and typography — presented in a single cohesive direction built around your positioning." },
      { step: "03", title: "Applications", description: "The identity is applied to your most critical touchpoints: pitch deck template, LinkedIn, business cards, and email — the assets you need on day one." },
      { step: "04", title: "Guidelines + Launch", description: "You receive a brand guidelines document and every asset in every format — ready to hand to developers, printers, or marketing agencies immediately." },
    ],
    whoFor: [
      "Pre-launch startups building their first brand",
      "Seed-stage founders preparing for investor meetings",
      "B2B startups targeting enterprise clients",
      "SaaS companies launching their product",
      "Fintech and proptech startups",
      "Founders with a DIY logo that no longer reflects their ambition",
    ],
    faqs: [
      { q: "How much does startup branding cost?", a: "Startup branding starts at $500 for a core identity package — logo, colour palette, typography, and a one-page brand reference. A full startup brand system with guidelines, pitch deck template, and social templates is $1,200. Bespoke packages are quoted based on scope. All prices are fixed — no hourly rates." },
      { q: "Do startups really need professional branding?", a: "Yes — especially in the first 12 months. Your brand is your first impression with every customer, investor, partner, and hire. A weak brand doesn't just look unprofessional — it costs you deals. Studies show that consistent brand presentation increases revenue by an average of 23% (Lucidpress, 2022). For a startup competing on credibility you haven't yet earned through reputation, your brand does the trust-building work." },
      { q: "What's the difference between startup branding and regular branding?", a: "Startup branding is optimised for speed, flexibility, and credibility under resource constraints. The identity needs to work across digital touchpoints first (website, pitch decks, LinkedIn, product UI), be scalable as the brand evolves, and communicate ambition even when the team is small. We build startup brands to look $10M even at $100K ARR." },
      { q: "Should I brand before or after building the product?", a: "Before — ideally. Your brand shapes how you name features, write copy, design your UI, and pitch to investors. A brand built after the product is often retrofitted awkwardly. Even a simple brand foundation (logo, colour, typography) before your first landing page means everything you build is coherent from the start." },
      { q: "Can you design a brand for a pre-revenue startup?", a: "Yes — most of our startup clients are pre-revenue. You don't need customers to start building brand equity. In fact, a strong brand before launch helps you acquire your first customers faster, because you look credible before you've proven it through track record." },
      { q: "How long does startup branding take?", a: "Core identity design takes 10–14 business days. Full brand system including guidelines and templates takes 3 weeks. We offer expedited timelines for startups with imminent launches or pitch meetings — contact us with your deadline and we'll confirm availability." },
      { q: "Do you work with US and UK startups?", a: "Yes — we work with startups across the US, UK, Canada, and Australia. We operate entirely remotely, so there's no location constraint. Most of our startup clients are in New York, San Francisco, London, Toronto, and Sydney." },
    ],
    relatedServices: [
      { title: "Brand Identity Design", href: "/lp/brand-identity-design" },
      { title: "Logo Design Service", href: "/lp/logo-design-service" },
      { title: "Web Design for Startups", href: "/lp/web-design-for-startups" },
      { title: "Brand Guidelines Design", href: "/lp/brand-guidelines-design" },
    ],
    internalLinks: [
      { title: "Brand strategy for startups", href: "/blog/brand-strategy-pre-launch" },
      { title: "Brand strategy for growth stage", href: "/blog/brand-strategy-for-growth-stage" },
      { title: "How to build brand trust", href: "/blog/how-to-build-brand-trust" },
      { title: "Visual identity guide", href: "/blog/visual-identity-guide" },
      { title: "Get a free quote", href: "/contact" },
    ],
    stats: [
      { value: "500+", label: "Brands launched" },
      { value: "3 weeks", label: "Full system delivery" },
      { value: "$500", label: "Starting price" },
      { value: "5.0/5", label: "Clutch rating" },
    ],
  },

  {
    slug: "small-business-branding",
    title: "Small Business Branding",
    tagline: "Professional branding for small businesses — so you compete on quality, not just price.",
    metaTitle: "Small Business Branding Service — From $150 | Evoke Studio",
    metaDescription: "Small business branding from $150. Professional logo design, brand identity, and brand guidelines for small businesses in the US, UK, Canada, and Australia. Free quote in 24hrs.",
    primaryKeyword: "small business branding",
    startingPrice: "$150",
    turnaround: "5–14 business days",
    heroDescription: "Small business branding levels the playing field. A professionally designed logo and consistent visual identity means your business looks as credible as your much larger competitors — without the agency price tag. Our small business branding service is built around what you actually need: a sharp, usable identity delivered fast.",
    whatIs: {
      question: "What is small business branding?",
      answer: "Small business branding is the process of creating a cohesive visual identity for an independent or owner-operated business — covering your logo, colours, typography, and the consistent way you present yourself across every customer touchpoint. For small businesses, branding does something specific: it signals that you take your work seriously. Customers make split-second judgements about a business based on how it looks. A professional brand identity means you're judged on your service quality — not your graphic design.",
    },
    included: [
      "Custom logo design (mark or wordmark — your choice)",
      "Colour palette with exact colour codes (HEX, RGB, CMYK)",
      "Typography recommendation (free and paid font options)",
      "Logo in all variants: primary, reversed, stacked, horizontal",
      "SVG, PNG, JPEG — ready for website, print, and social",
      "Basic brand reference card (one-page PDF)",
      "Free revision round to ensure it's exactly right",
    ],
    process: [
      { step: "01", title: "Brief", description: "You fill out a 10-minute brand brief — your business, your customers, the feeling you want your brand to create, and examples you like." },
      { step: "02", title: "Design", description: "We design 2–3 logo concepts built around your brief, industry, and competitive landscape. Delivered within 5 business days." },
      { step: "03", title: "Refine", description: "You choose a direction. We refine until it's perfect — adjusting colours, proportions, and details until every element is right." },
      { step: "04", title: "Files", description: "You receive every file you'll ever need — for your website, social profiles, printed materials, and signage — organised and labelled clearly." },
    ],
    whoFor: [
      "Tradespeople and service businesses",
      "Retail and e-commerce shops",
      "Restaurants, cafés, and hospitality businesses",
      "Freelancers and consultants",
      "Healthcare and wellness practitioners",
      "Real estate agents and property managers",
    ],
    faqs: [
      { q: "How much does small business branding cost?", a: "Small business branding starts at $150 for a logo design. A complete brand identity package — logo, colours, typography, and a brand reference card — starts at $500. Full brand identity with guidelines and stationery templates starts at $1,200. All prices are fixed and confirmed before work begins." },
      { q: "Can small businesses afford professional branding?", a: "Yes. Our small business branding service is specifically priced for owner-operated businesses — starting at $150 for a standalone logo, with complete identity packages at $500. The ROI of professional branding for small businesses is well-documented: consistent brand presentation generates 3.5x more brand visibility (Forbes) and directly impacts what customers are willing to pay." },
      { q: "What's better — a DIY logo or a professional design?", a: "Professional design, consistently. DIY logos — from Canva, Looka, or similar tools — use template elements shared with thousands of other businesses. They're often technically unsuitable for print, embroidery, or large-format use. A professionally designed logo is unique to your business, delivered in every file format you'll ever need, and built to look good at any size." },
      { q: "Do I need a brand identity or just a logo?", a: "A logo alone is a start — but a brand identity is what makes your business look consistent everywhere. With just a logo, you'll likely choose random colours and fonts for different applications. With a brand identity, every touchpoint — your website, social media, proposals, invoices — looks like it comes from the same place. Most small businesses benefit from at least a core identity package (logo + colour + typography)." },
      { q: "How long does small business branding take?", a: "Logo design: 5–7 business days for initial concepts, 10–14 total from brief to final files. Full brand identity: 3 weeks. We can accommodate urgent timelines — contact us with your deadline." },
      { q: "Do you design logos for local businesses?", a: "Yes — we work with local businesses across the US, UK, Canada, and Australia. Whether you're a plumber in New York, a café owner in London, or a real estate agent in Sydney, we design brands that resonate with local customers while standing up to any competitor." },
    ],
    relatedServices: [
      { title: "Logo Design Service", href: "/lp/logo-design-service" },
      { title: "Brand Identity Design", href: "/lp/brand-identity-design" },
      { title: "Brand Guidelines Design", href: "/lp/brand-guidelines-design" },
    ],
    internalLinks: [
      { title: "Why your brand looks unprofessional", href: "/blog/why-your-brand-looks-unprofessional" },
      { title: "How to make your brand stand out", href: "/blog/how-to-make-your-brand-stand-out" },
      { title: "Brand personality guide", href: "/blog/brand-personality-guide" },
      { title: "Brand photography guide", href: "/blog/brand-photography-guide" },
      { title: "Get a free quote", href: "/contact" },
    ],
    stats: [
      { value: "500+", label: "Small businesses branded" },
      { value: "5–7 days", label: "Logo delivery" },
      { value: "$150", label: "Starting price" },
      { value: "5.0/5", label: "Clutch rating" },
    ],
  },

  {
    slug: "logo-redesign-service",
    title: "Logo Redesign Service",
    tagline: "Modernise your logo without losing the brand equity you've spent years building.",
    metaTitle: "Logo Redesign Service — From $200 | Evoke Studio",
    metaDescription: "Logo redesign from $200. Refresh or fully rebrand your existing logo while preserving brand recognition. SVG, AI, EPS, PDF delivered in 7–10 days. Free brand audit with every project.",
    primaryKeyword: "logo redesign service",
    startingPrice: "$200",
    turnaround: "7–10 business days",
    heroDescription: "A logo redesign is one of the highest-leverage investments a growing business can make. As your company evolves, your logo needs to reflect where you're going — not where you started. Our logo redesign service modernises your visual identity while preserving what makes your brand recognisable to the customers who already trust you.",
    whatIs: {
      question: "What is a logo redesign service?",
      answer: "A logo redesign service is the professional process of updating, modernising, or completely reworking an existing logo — ranging from a subtle refresh (adjusting proportions, cleaning up details, updating colours) to a full redesign (new mark, new wordmark, new visual direction). The goal is to bring your visual identity in line with where your brand is today, without throwing away the brand recognition you've earned. A skilled logo redesign preserves the equity in your existing mark — what customers already associate with your brand — while solving whatever problems the current logo has: it looks dated, doesn't scale, doesn't work in print, or no longer reflects your positioning.",
    },
    included: [
      "Brand equity audit — what to keep, what to change",
      "Logo redesign (refresh or full rebrand — your scope)",
      "Modernised colour palette with exact colour codes",
      "Updated typography to match new direction",
      "All logo variants: primary, reversed, stacked, horizontal, icon-only",
      "SVG, AI, EPS, PDF, PNG, JPEG file package",
      "Side-by-side before/after presentation",
      "Free revision round on final direction",
    ],
    process: [
      { step: "01", title: "Audit", description: "We review your existing logo: what works, what doesn't, what has brand equity worth preserving, and what's holding your business back visually." },
      { step: "02", title: "Direction", description: "We propose a redesign scope — refresh, evolution, or full rebrand — with a rationale for each option. You choose the direction that fits your goals." },
      { step: "03", title: "Redesign", description: "We execute the redesign with the same precision as any new logo project — every curve, spacing, and colour decision made deliberately." },
      { step: "04", title: "Delivery", description: "You receive the redesigned logo in every file format, plus a before/after presentation showing the evolution — useful for announcing the refresh to customers." },
    ],
    whoFor: [
      "Established businesses whose logo looks dated",
      "Companies that have outgrown a DIY or low-cost logo",
      "Brands expanding into new markets or premium segments",
      "Businesses after a merger, acquisition, or pivot",
      "Franchises standardising brand across locations",
      "Businesses preparing for website or marketing refresh",
    ],
    faqs: [
      { q: "How much does a logo redesign cost?", a: "Logo redesign starts at $200 for a refresh of an existing mark. A full logo rebrand — new mark, new wordmark, new visual language — starts at $350. If the redesign extends to a full brand identity update (colours, typography, guidelines), it starts at $700. All prices are fixed. You receive a quote before work begins." },
      { q: "What is the difference between a logo refresh and a logo redesign?", a: "A logo refresh is an evolution — you keep the core concept and recognition, but modernise the execution: cleaner lines, updated colours, better proportions, better scalability. A logo redesign (or rebrand) is more significant — the concept changes, not just the execution. We recommend a refresh when your logo has strong brand recognition. We recommend a full redesign when the current logo no longer reflects your business, category, or audience." },
      { q: "Will my customers recognise the new logo?", a: "That depends on the scope of the redesign. For a refresh, the new logo should be immediately recognisable — customers notice it's better without necessarily articulating what changed. For a full rebrand, you'll communicate the change proactively. We provide a before/after presentation and guidance on rolling out the new mark." },
      { q: "Do I need to rebrand my whole business or just the logo?", a: "It depends on what's driving the redesign. If the issue is only the logo mark, a standalone redesign is sufficient. If your business has evolved significantly — new positioning, new market, new name — you may benefit from updating the full visual identity system at the same time. We'll assess your situation and recommend the right scope." },
      { q: "How long does a logo redesign take?", a: "Logo redesign takes 7–10 business days from brief to final files. Full brand identity updates take 3–4 weeks. Rush timelines are available for businesses with imminent launch dates." },
      { q: "Can you redesign a logo if I don't have the original files?", a: "Yes — we work from whatever you have, including low-resolution images. We'll reconstruct the original logo as part of the redesign process, then evolve it from there. This is common for businesses that lost their original design files." },
    ],
    relatedServices: [
      { title: "Logo Design Service", href: "/lp/logo-design-service" },
      { title: "Brand Identity Design", href: "/lp/brand-identity-design" },
      { title: "AI Logo Vectorization", href: "/lp/ai-logo-vectorization" },
    ],
    internalLinks: [
      { title: "When to rebrand your business", href: "/blog/when-to-rebrand-your-business" },
      { title: "How to rebrand your business", href: "/blog/how-to-rebrand-your-business" },
      { title: "Rebranding mistakes to avoid", href: "/blog/rebranding-mistakes-to-avoid" },
      { title: "Rebranding cost guide", href: "/blog/rebranding-cost-guide" },
      { title: "Get a free quote", href: "/contact" },
    ],
    stats: [
      { value: "200+", label: "Logos redesigned" },
      { value: "7–10 days", label: "Turnaround" },
      { value: "$200", label: "Starting price" },
      { value: "5.0/5", label: "Clutch rating" },
    ],
  },

  {
    slug: "brand-guidelines-design",
    title: "Brand Guidelines Design",
    tagline: "Give your brand the rulebook it needs to stay consistent — no matter who's using it.",
    metaTitle: "Brand Guidelines Design Service — From $300 | Evoke Studio",
    metaDescription: "Brand guidelines design from $300. Professional brand style guide covering logo usage, colour palette, typography, imagery, and tone of voice. PDF delivered in 5–7 days. Free quote.",
    primaryKeyword: "brand guidelines design",
    startingPrice: "$300",
    turnaround: "5–7 business days",
    heroDescription: "Brand guidelines — also called a brand style guide or brand standards document — are the rulebook that keeps your brand consistent across every touchpoint, designer, and platform. Our brand guidelines design service creates a professional document your team, developers, agencies, and vendors can follow without guessing.",
    whatIs: {
      question: "What are brand guidelines?",
      answer: "Brand guidelines (also called a brand style guide, brand standards document, or brand manual) are a formal document that defines the rules for how your brand's visual identity is used. This includes: how the logo can and can't be displayed, which exact colours are used and where, which typefaces are used for different applications, how imagery and photography should look and feel, and sometimes tone of voice and messaging rules. Brand guidelines exist because without them, every designer, developer, social media manager, and marketing agency that touches your brand will make different decisions — and over time, your brand becomes inconsistent, diluted, and unrecognisable.",
    },
    included: [
      "Logo usage rules — clear space, minimum size, approved backgrounds",
      "Logo misuse examples — what never to do",
      "Primary and secondary colour palette with Pantone, CMYK, RGB, HEX codes",
      "Typography system — typefaces, weights, sizing hierarchy, usage rules",
      "Imagery and photography style guidance",
      "Iconography and graphic element usage rules",
      "Brand voice and tone overview (where applicable)",
      "Application examples (business card, social, website, email)",
      "20–30 page professionally designed PDF",
      "Editable source file (Figma or Adobe InDesign)",
    ],
    process: [
      { step: "01", title: "Asset Audit", description: "We review your existing brand assets — logo files, colours, fonts — and identify what's defined, what's inconsistent, and what needs formalising." },
      { step: "02", title: "Structure", description: "We plan the guidelines document: which sections are needed, the order of presentation, and what examples and do's/don'ts to include for your specific use cases." },
      { step: "03", title: "Design", description: "We design the brand guidelines document itself — a professionally laid-out PDF that reflects your brand while being clear and easy to follow." },
      { step: "04", title: "Delivery", description: "You receive the PDF guidelines, plus an editable source file (Figma or InDesign) so you can update it as your brand evolves." },
    ],
    whoFor: [
      "Businesses hiring their first designer or marketing hire",
      "Companies working with external agencies or freelancers",
      "Brands with multiple locations or franchise operations",
      "Startups that have a logo but no formal brand standards",
      "Businesses preparing to launch a new website or campaign",
      "Companies going through rebrand who need new documentation",
    ],
    faqs: [
      { q: "How much do brand guidelines cost?", a: "Brand guidelines design starts at $300 for a concise brand reference document (8–12 pages) covering the essentials: logo usage, colour palette, and typography. A comprehensive brand guidelines PDF (20–30 pages) with applications, imagery guidance, and tone of voice starts at $600. Enterprise-scale brand manuals for large organisations are quoted individually." },
      { q: "What should brand guidelines include?", a: "At minimum: logo usage rules and misuse examples, colour palette with exact codes (Pantone, CMYK, RGB, HEX), typography system with usage rules, and application examples. Comprehensive guidelines also include photography style, illustration guidelines, iconography, tone of voice, and template examples for common formats (email, social, presentations)." },
      { q: "How long does it take to create brand guidelines?", a: "A concise brand reference document takes 3–5 business days. A comprehensive brand guidelines PDF takes 5–7 business days. Large-scale brand manuals for enterprise organisations take 2–4 weeks depending on scope." },
      { q: "Do I need brand guidelines if I'm a small business?", a: "Yes — especially if you work with any external party: a web developer, social media manager, printer, or graphic designer. Without guidelines, everyone makes their own decisions about your brand. The result is inconsistency that erodes trust over time. Even a concise 8-page brand reference covers the essentials and costs less than one hour of a designer's time fixing misapplied branding." },
      { q: "What format will the brand guidelines be delivered in?", a: "You receive a professionally designed PDF you can share with anyone, plus an editable source file (Figma or Adobe InDesign) so you can maintain and update the document yourself. We also provide a web-ready compressed version for easy email sharing." },
      { q: "Can you create brand guidelines from an existing brand?", a: "Yes — this is the most common scenario. You have a logo and some visual assets, but nothing is formally documented. We audit what you have, standardise it, and produce a guidelines document that captures your current brand system accurately." },
    ],
    relatedServices: [
      { title: "Brand Identity Design", href: "/lp/brand-identity-design" },
      { title: "Logo Design Service", href: "/lp/logo-design-service" },
      { title: "Startup Branding", href: "/lp/startup-branding" },
    ],
    internalLinks: [
      { title: "Brand audit guide", href: "/blog/brand-audit-guide" },
      { title: "Brand architecture guide", href: "/blog/brand-architecture-guide" },
      { title: "Brand differentiation strategy", href: "/blog/brand-differentiation-strategy" },
      { title: "Visual identity guide", href: "/blog/visual-identity-guide" },
      { title: "Get a free quote", href: "/contact" },
    ],
    stats: [
      { value: "300+", label: "Brand guides delivered" },
      { value: "5–7 days", label: "Turnaround" },
      { value: "$300", label: "Starting price" },
      { value: "20–30pp", label: "Avg. document length" },
    ],
  },

  {
    slug: "web-design-for-startups",
    title: "Web Design for Startups",
    tagline: "Startup websites that convert visitors into customers, investors, and believers.",
    metaTitle: "Web Design for Startups — Next.js & React | Evoke Studio",
    metaDescription: "Web design for startups using Next.js, React, and Tailwind CSS. Fast, conversion-optimised, and brand-led websites built for founders who need to grow. Free quote in 24hrs.",
    primaryKeyword: "web design for startups",
    startingPrice: "$2,500",
    turnaround: "3–5 weeks",
    heroDescription: "Web design for startups is a specific discipline. You're not designing for a Fortune 500 with established brand equity — you're designing for a company that needs to build trust instantly, convert high-intent visitors, and scale without a redesign every year. Our startup web design process is brand-led, performance-first, and built on Next.js.",
    whatIs: {
      question: "What does web design for startups involve?",
      answer: "Web design for startups involves designing and building a website that serves multiple high-stakes audiences simultaneously: potential customers, investors, potential hires, and press. Unlike corporate website redesigns, startup web design starts from scratch or near-scratch, often without established brand equity to lean on. This means every design decision — layout, copy architecture, visual hierarchy, calls to action — has to work harder. The best startup websites look credible before the company has the track record to justify it, convert visitors into leads or sign-ups with minimal friction, and load fast enough to not lose people before they read a word.",
    },
    included: [
      "Brand-led design (we build from your identity or create it)",
      "Custom Next.js website (no page-builder tools)",
      "Responsive design for mobile, tablet, and desktop",
      "Homepage, About, Services/Product, and Contact pages as standard",
      "Conversion-optimised layout and call-to-action hierarchy",
      "Performance-optimised (Core Web Vitals: 90+ Lighthouse score)",
      "SEO technical foundation (meta tags, sitemap, schema markup)",
      "Blog or resource section (optional)",
      "Contact form with email integration",
      "Vercel deployment and DNS configuration",
      "1-month post-launch support",
    ],
    process: [
      { step: "01", title: "Discovery", description: "We define your website goals, target audience, conversion actions, and content architecture before any design begins." },
      { step: "02", title: "Design", description: "We design your website in Figma — every page, every breakpoint, every interaction — and present it for review before writing a line of code." },
      { step: "03", title: "Development", description: "We build in Next.js — fast, scalable, and SEO-friendly by default. Every component is custom; no themes or page builders." },
      { step: "04", title: "Launch", description: "We deploy to Vercel, configure your domain, test across devices and browsers, and hand over a fully documented, maintainable codebase." },
    ],
    whoFor: [
      "Pre-launch startups building their first website",
      "Seed and Series A startups that outgrew a template",
      "B2B SaaS companies building a marketing site",
      "Fintech and proptech startups",
      "Founders preparing for investor pitches",
      "Companies where the website is the primary sales channel",
    ],
    faqs: [
      { q: "How much does web design for startups cost?", a: "Startup website design and development starts at $2,500 for a focused 4–5 page marketing site (homepage, about, services, contact). A full marketing site with blog, case studies, and advanced interactions starts at $5,000. E-commerce and product-led websites are quoted individually. All projects are fixed-price — no hourly billing." },
      { q: "Why Next.js for startup websites?", a: "Next.js is the industry standard for high-performance marketing sites and web apps. It gives you server-side rendering for SEO, static generation for speed, and a React foundation that your engineering team can extend. Your marketing site and web app can share code, design system, and infrastructure. It also deploys on Vercel — the fastest global edge network — in under 2 minutes." },
      { q: "How long does it take to build a startup website?", a: "A focused startup marketing site (4–5 pages) takes 3–5 weeks from discovery to launch. Larger sites with blog, case studies, and custom interactions take 6–8 weeks. We can compress timelines for startups with hard launch deadlines — contact us with your date." },
      { q: "Will my website rank on Google and Bing?", a: "We build a strong technical SEO foundation into every site: clean URL structure, proper meta tags, structured data (schema markup), fast load times, sitemap submission, and mobile-first design. Ranking for competitive keywords takes content and time — but the technical foundation we build means nothing is holding your SEO back." },
      { q: "Can you design the brand and website together?", a: "Yes — and it's our preferred approach. When brand identity and website design are developed together, the result is cohesive. We offer combined brand + website packages that start at $3,500 for a core identity and a focused marketing site." },
      { q: "Do you work with US and UK startups?", a: "Yes. We have worked with startups in New York, San Francisco, London, Toronto, and Sydney. All projects are managed remotely via Figma, GitHub, and video calls. We're timezone-flexible for US, UK, Canadian, and Australian clients." },
    ],
    relatedServices: [
      { title: "Startup Branding", href: "/lp/startup-branding" },
      { title: "Brand Identity Design", href: "/lp/brand-identity-design" },
      { title: "Small Business Branding", href: "/lp/small-business-branding" },
    ],
    internalLinks: [
      { title: "Web design for professional services", href: "/blog/web-design-for-professional-services" },
      { title: "Brand strategy for startups", href: "/blog/brand-strategy-pre-launch" },
      { title: "See live websites we built", href: "/services" },
      { title: "Brand for enterprise sales", href: "/blog/brand-for-enterprise-sales" },
      { title: "Get a free quote", href: "/contact" },
    ],
    stats: [
      { value: "30+", label: "Startup sites launched" },
      { value: "90+", label: "Lighthouse score" },
      { value: "$2,500", label: "Starting price" },
      { value: "3–5 wks", label: "Avg. timeline" },
    ],
  },

  {
    slug: "branding-agency-usa",
    title: "Branding Agency USA",
    tagline: "A US-focused branding agency for businesses that compete on credibility, not just price.",
    metaTitle: "Branding Agency USA — Logo & Identity Design | Evoke Studio",
    metaDescription: "US branding agency specialising in logo design, brand identity, and brand strategy for American businesses. Fixed pricing from $150. Free quote in 24hrs. 5.0/5 on Clutch.",
    primaryKeyword: "branding agency USA",
    startingPrice: "$150",
    turnaround: "5–14 business days",
    heroDescription: "As a branding agency serving US businesses, Evoke Studio works with startups, small businesses, and professional services firms across New York, Los Angeles, Chicago, San Francisco, Boston, Austin, and beyond. Our work is strategy-first, design-led, and priced transparently — no retainers, no hourly billing, no surprises.",
    whatIs: {
      question: "What does a US branding agency do?",
      answer: "A US branding agency creates and manages the visual identity of businesses operating in the American market. This includes logo design, brand identity systems, brand strategy, brand guidelines, and the application of those assets across every customer touchpoint. For US businesses specifically, a branding agency understands the competitive landscape in American markets: the visual conventions of your industry category, the expectations of US consumers, and how to position your brand against domestic and international competitors. Evoke Studio serves US clients exclusively on a remote basis — delivering professional-grade branding without the overhead of a large agency.",
    },
    included: [
      "Brand strategy and positioning (US market focus)",
      "Custom logo design built for the American market",
      "Colour palette optimised for US industry conventions",
      "Typography system aligned with US brand standards",
      "Brand guidelines document",
      "Stationery and digital application templates",
      "USPTO trademark guidance (we advise; you file)",
      "Full file package: SVG, AI, EPS, PDF, PNG, JPEG",
    ],
    process: [
      { step: "01", title: "Strategy", description: "We define your brand positioning within your specific US market — your category, competitors, and the customers you need to win." },
      { step: "02", title: "Identity Design", description: "We design your visual identity — logo, colour, typography — built specifically for how US customers in your industry judge credibility." },
      { step: "03", title: "Application", description: "The identity is applied across the touchpoints that matter most for US businesses: website, LinkedIn, business cards, proposals, and signage." },
      { step: "04", title: "Launch", description: "You receive every asset, every format, and brand guidelines — ready to hand to any US developer, printer, or marketing agency." },
    ],
    whoFor: [
      "US startups launching their first brand",
      "American small businesses rebranding for growth",
      "Professional services firms in New York, LA, Chicago, Boston",
      "US companies preparing for Series A or B fundraising",
      "American franchises standardising brand across locations",
      "US e-commerce brands competing for premium positioning",
    ],
    faqs: [
      { q: "How much does a branding agency in the USA charge?", a: "US branding agency pricing varies widely. Large agencies in New York or San Francisco charge $50,000–$500,000+ for a rebrand. Mid-size agencies charge $10,000–$50,000. Boutique agencies like Evoke Studio charge $500–$5,000 for complete identity systems — delivering agency-quality work at transparent, fixed prices without the overhead." },
      { q: "Where are you based — are you a US branding agency?", a: "Evoke Studio operates globally and serves US clients across all 50 states. While we are not physically based in a US city, every project we take is managed to US market standards, US pricing conventions, and with an understanding of US industry visual language. All communication is in US business hours. We have worked with clients in New York, San Francisco, Los Angeles, Chicago, Austin, Boston, and beyond." },
      { q: "Do you understand the US market?", a: "Yes. The majority of our clients are US-based. We understand the visual conventions across key US industries — fintech, proptech, management consulting, professional services, healthcare, and consumer brands. We also understand what US investors, customers, and partners expect from a brand presentation." },
      { q: "Can you help with trademark registration in the USA?", a: "We provide guidance on trademark considerations during the design process — flagging if a proposed mark is similar to registered marks in your category. For USPTO filing itself, we recommend working with a US trademark attorney. We can recommend specialists if needed." },
      { q: "How do I work with a branding agency remotely?", a: "Our entire process is remote: brief via form, concepts via PDF presentation, revisions via marked-up PDF or Figma, delivery via organised file package. Most clients find the remote process faster and more efficient than in-person agency meetings. We use video calls at key milestones and respond to all messages within one business day." },
      { q: "What industries do you serve in the USA?", a: "We have served US clients in fintech, proptech, management consulting, wealth management, legal services, healthcare, real estate, technology (SaaS), e-commerce, hospitality, and professional services. We do not take on projects in categories we don't understand — if your industry is outside our experience, we'll tell you upfront." },
    ],
    relatedServices: [
      { title: "Brand Identity Design", href: "/lp/brand-identity-design" },
      { title: "Startup Branding", href: "/lp/startup-branding" },
      { title: "Small Business Branding", href: "/lp/small-business-branding" },
      { title: "Logo Design Service", href: "/lp/logo-design-service" },
    ],
    internalLinks: [
      { title: "Brand strategy for management consulting", href: "/blog/brand-strategy-for-management-consulting" },
      { title: "Brand strategy for wealth management", href: "/blog/brand-strategy-for-wealth-management" },
      { title: "Brand strategy for real estate agencies", href: "/blog/brand-strategy-for-real-estate-agencies" },
      { title: "Personal branding for consultants", href: "/blog/personal-branding-for-consultants" },
      { title: "Get a free quote", href: "/contact" },
    ],
    stats: [
      { value: "USA", label: "Primary market" },
      { value: "500+", label: "Projects delivered" },
      { value: "$150", label: "Starting price" },
      { value: "5.0/5", label: "Clutch rating" },
    ],
  },

  {
    slug: "ai-logo-cleanup",
    title: "AI Logo Cleanup Service",
    tagline: "Fix the problems in your AI-generated logo — inconsistent shapes, broken letterforms, unusable details.",
    metaTitle: "AI Logo Cleanup Service — From $75 | Evoke Studio",
    metaDescription: "AI logo cleanup from $75. Fix proportion issues, letterform errors, inconsistent shapes, and unsuitable details in Midjourney, DALL·E, and Ideogram logos. Free quote in 2hrs.",
    primaryKeyword: "AI logo cleanup",
    startingPrice: "$75",
    turnaround: "24–48 hours",
    heroDescription: "AI logo cleanup is the process of correcting the visual errors that AI image generators introduce into logo designs — distorted letterforms, inconsistent stroke weights, broken symmetry, details that vanish at small sizes. Our AI logo cleanup service fixes these problems and delivers a production-ready file that works everywhere your brand needs to appear.",
    whatIs: {
      question: "What is AI logo cleanup?",
      answer: "AI logo cleanup is the process of fixing visual problems in AI-generated logos before they are used commercially. AI image generators like Midjourney, DALL·E, and Ideogram produce impressive-looking logos — but on close inspection, they often have issues that make them unusable for professional use: letterforms that are distorted or unreadable, shapes with inconsistent stroke weights, elements that look fine at large sizes but disappear or blur at small sizes, colour areas that are inconsistent or technically incorrect. AI logo cleanup involves manually identifying and correcting these issues — rebuilding problem areas, standardising proportions, cleaning up details — and delivering a file that is both visually correct and technically production-ready.",
    },
    included: [
      "Detailed inspection of all logo elements at multiple scales",
      "Manual correction of distorted letterforms and typography",
      "Stroke weight standardisation across all elements",
      "Symmetry correction on marks and icons",
      "Simplification of overcomplex details unsuitable for small sizes",
      "Colour standardisation (exact HEX, RGB, CMYK matching)",
      "Vector file output (SVG, AI, EPS, PDF, PNG, JPEG)",
      "Side-by-side before/after comparison",
    ],
    process: [
      { step: "01", title: "Submit", description: "Send your AI-generated logo and describe any specific problems you've noticed or concerns about how it will be used." },
      { step: "02", title: "Audit", description: "We conduct a detailed inspection across all elements — letterforms, shapes, colours, proportions — and send a fixed quote within 2 hours." },
      { step: "03", title: "Cleanup", description: "Every identified issue is corrected manually. We rebuild problem areas from scratch where necessary, never applying auto-fix shortcuts." },
      { step: "04", title: "Delivery", description: "You receive a comparison showing before and after, plus the corrected logo in every file format within 24–48 hours." },
    ],
    whoFor: [
      "Founders who generated a logo with AI tools",
      "Designers cleaning up client-submitted AI logos",
      "Businesses preparing AI logos for print production",
      "Brands needing embroidery or merchandise-ready files",
      "Startups before their first website or pitch deck launch",
      "Agencies handling AI logo cleanup at scale",
    ],
    faqs: [
      { q: "How much does AI logo cleanup cost?", a: "AI logo cleanup starts at $75 for a simple wordmark or icon with minor issues. Most cleanup projects fall in the $75–$200 range. Complex marks with extensive letterform problems, multiple elements, or detailed illustrations are quoted individually — you'll receive a fixed price within 2 hours of submitting your logo." },
      { q: "What kinds of problems can AI logo cleanup fix?", a: "We fix distorted, unreadable, or inconsistent letterforms; uneven stroke weights; broken symmetry in marks and icons; overcomplex details that won't reproduce at small sizes; colour inconsistencies; and proportion issues that make the logo look unbalanced. We also fix logos that look fine on screen but won't print correctly." },
      { q: "Is AI logo cleanup different from AI logo vectorization?", a: "Yes — they are related but different. Vectorization converts a raster (pixel) image into vector paths. Cleanup fixes the visual and technical problems in the design itself. Many AI logo projects require both: first cleanup (fixing what's wrong), then vectorization (converting to professional file formats). We offer both, and a combined package is usually the most efficient approach." },
      { q: "What if the logo is too problematic to clean up?", a: "Occasionally, an AI-generated logo has such fundamental issues — unreadable text, proportions that can't be fixed without a redesign — that cleanup isn't the right solution. In those cases, we'll tell you clearly and recommend a logo redesign instead. We don't charge for the audit if we can't deliver a clean result." },
      { q: "How long does AI logo cleanup take?", a: "Most cleanup projects are delivered within 24–48 hours of quote approval. Simple fixes can be turned around in the same business day. Rush delivery is available." },
      { q: "What AI logo generators do you work with?", a: "We work with logos generated by Midjourney, DALL·E 3, Adobe Firefly, Ideogram, Stable Diffusion, Leonardo AI, and any other AI image tool. The source doesn't affect our process — we work from the output image." },
    ],
    relatedServices: [
      { title: "AI Logo Vectorization", href: "/lp/ai-logo-vectorization" },
      { title: "Logo Redesign Service", href: "/lp/logo-redesign-service" },
      { title: "Logo Design Service", href: "/lp/logo-design-service" },
    ],
    internalLinks: [
      { title: "AI logo vectorization service", href: "/services/ai-logo-vectorization" },
      { title: "AI logo cleanup service", href: "/services/ai-logo-cleanup" },
      { title: "Typography reconstruction", href: "/services/typography-reconstruction" },
      { title: "See before and after examples", href: "/portfolio" },
      { title: "Get a free quote", href: "/contact" },
    ],
    stats: [
      { value: "500+", label: "AI logos cleaned" },
      { value: "24–48hrs", label: "Turnaround" },
      { value: "$75", label: "Starting price" },
      { value: "100%", label: "Manual process" },
    ],
  },
];
